import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./components/NavBar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html>
            <body className="min-h-full flex flex-col bg-primary-bg">
                <NavBar />
                {children}
            </body>
        </html>
    );
}
